name: OceanColor
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - click
  - h5netcdf
  - h5py
  - hdf5
  - loky>=2.8
  - netcdf4>=1.5.4
  - numpy=1.17
  - pandas=1.0
  - proj
  - pytables
  - requests
  - xarray=1.16
  - pytest>=5.4
