name: OceanColor
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.8,<3.9
  - click
  - h5netcdf
  - h5py
  - hdf5
  - loky=2.9.0
  - netcdf4 >=1.5.4
  - numpy=1.19.2
  - pandas=1.2.2
  - proj
  - pytables
  - requests
  - xarray=1.16.2
  - pytest>=5.4
