name: OceanColor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "7 18 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Install System requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y libhdf5-dev libnetcdf-dev

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .[dev,parallel,s3]

    - name: Cache sample data
      id: cache-samples
      uses: actions/cache@v3
      with:
        path: |
          MODIS-Aqua/L3m/2017/01/12/AQUA_MODIS.20170112.L3m.DAY.CHL.chlor_a.4km.nc
          MODIS-Aqua/L2/2016/08/31/AQUA_MODIS.20160831T221001.L2.OC.nc
          MODIS-Aqua/L2/2016/09/01/AQUA_MODIS.20160901T211500.L2.OC.nc
          MODIS-Aqua/L2/2017/01/12/AQUA_MODIS.20170112T213500.L2.OC.nc
          MODIS-Terra/L3m/2004/01/06/TERRA_MODIS.20040106.L3m.DAY.CHL.chlor_a.4km.nc
          VIIRS-SNPP/L2/2017/01/13/SNPP_VIIRS.20170113T002400.L2.OC.nc
        key: ${{ runner.os }}-CHL

    - name: Test with pytest
      run: |
        pytest -v tests
      env:
        NASA_USERNAME: ${{ secrets.NASA_USERNAME }}
        NASA_PASSWORD: ${{ secrets.NASA_PASSWORD }}
