name: OceanColor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .

    - name: Cache sample data
      id: cache-samples
      uses: actions/cache@v2
      with:
        path: |
          A2017012213500.L2_LAC_OC.nc
          A2017012.L3m_DAY_CHL_chlor_a_4km.nc
        key: ${{ runner.os }}-CHL

    - name: Test with pytest
      run: |
        pytest tests
      env:
        NASA_USERNAME: ${{ secrets.NASA_USERNAME }}
        NASA_PASSWORD: ${{ secrets.NASA_PASSWORD }}
